### ISSUE TITLE
spam in log file

### ISSUE THREAD

**Issue by KES777** [miyagawa/Plack-Middleware-Debug#24]
Can not figure out from where it is comming, so post here. If it is your module please fix. Thank you.

I just use something from box `app.psgi`:

    use HTML::Mason::PSGIHandler;

    my $h = HTML::Mason::PSGIHandler->new(
           comp_root => "/home/feelsafe/public_html/www",
    );

    my $app = sub {
           my $env = shift;
           $h->handle_psgi($env);
    };

    use Plack::Builder;

    builder {
        enable "StackTrace";
        enable "Debug";
        enable "Debug::HTML::Mason";
        enable "Debug::Session";
        $app;
    };

and `/test.html`

	<%flags>
	inherit => undef
	</%flags>

	% die "Hello";

And in `uwsgi.log` file I have:

```
----------------------------------------------------------------------------
Use of uninitialized value in concatenation (.) or string at line 11 in template passed from /usr/share/perl5/Plack/Middl
eware/Debug.pm at line 118.
----------------------------------------------------------------------------
   9:     }
  10: </script>
  11: <script type="text/javascript" src="<%= $stash->{BASE_URL} %>/debug_toolbar/toolbar.min.js"></script>
  12: <script type="text/javascript" charset="utf-8">
  13:     // Now that jQuery is done loading, put the '$' variable back to what it was...
----------------------------------------------------------------------------
Use of uninitialized value $_MT_T in substitution (s///) at line 17 in template passed from /usr/share/perl5/Plack/Middle
ware/Debug.pm at line 118.
----------------------------------------------------------------------------
  15: </script>
  16: <style type="text/css">
  17:     @import url(<%= $stash->{BASE_URL} %>/debug_toolbar/toolbar.min.css);
  18: </style>
  19: <div id="plDebug">
----------------------------------------------------------------------------
Use of uninitialized value in concatenation (.) or string at line 17 in template passed from /usr/share/perl5/Plack/Middl
eware/Debug.pm at line 118.
----------------------------------------------------------------------------
  15: </script>
  16: <style type="text/css">
  17:     @import url(<%= $stash->{BASE_URL} %>/debug_toolbar/toolbar.min.css);
  18: </style>
  19: <div id="plDebug">
----------------------------------------------------------------------------
```

**Comment by miyagawa** [comment]
You have to set `SCRIPT_NAME` environment variable in PSGI. Consult uwsgi doc for how to set it.

**Comment by KES777** [comment]
I know, that is not right place, but you can save ton time and nerves for developers if you drom line to logthat:

`warn 'You have to set SCRIPT_NAME environment variable in PSGI. Consult uwsgi doc for how to set it.'   unless SCRIPT_NAME`
