### ISSUE TITLE
Debug panel is not showed

### ISSUE THREAD

**Issue by KES777** [miyagawa/Plack-Middleware-Debug#28]
Running application the debug panel is not showed. Returned HMLT has only "Hello World"
No errors or warning messages appeared.
'Hi' message is successfully logged

```Perl
use Modern::Perl;
use HTML::Mason::PSGIHandler;

use Log::Log4perl;
Log::Log4perl->init( '/home/user/public_html/log4perl.conf' );

my $app2 = sub {
    my $env =  shift;

    my $log =  Log::Log4perl::get_logger();
    $log->error( 'Hi' );

    return [
        '200',
        [ 'Content-Type' => 'text/plain' ],
        [ "Hello World" ],
    ];
};


use Plack::Builder;
use Plack::Middleware::Debug::Log4perl;
my $b =  builder {
    enable "Debug", panels => [ 'Log4perl' ];
    $app2;
}
```

**Comment by KES777** [comment]
Try to make patch, but this module is not hosted here, so distinguish please this sentence with NOTICE or/and bold 
```
---Also the code is injected directly before the </body> tag so if there is no such tag, the information will not be injected
+++NOTICE: Also the code is injected directly before the </body> tag so **if there is no such tag, the information will not be injected**
```

**Comment by miyagawa** [comment]
I don't think it's necessary, the doc is already there and clear.

**Comment by KES777** [comment]
But this is important note. With fast reading people may skip this (like me) and spend time to understand what is coming wrong ((

**Comment by oalders** [comment]
I think it is pretty clear, but it might not hurt to note it in a CAVEATS section.

**Comment by KES777** [comment]
https://github.com/miyagawa/Plack-Middleware-Debug/pull/29
