### ISSUE TITLE
Problems using jQuery 3.x

### ISSUE THREAD

**Issue by jomo666** [miyagawa/Plack-Middleware-Debug#35]
Having this simple `index.html`

```
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title>test</title>
</head>
	<body>
	Hello <span id="test">xxx</span>!
	<script   src="https://code.jquery.com/jquery-3.1.1.slim.min.js"   integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc="   crossorigin="anonymous"></script>
<!--
	<script   src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
	<script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
-->

<script>
$(document).ready(function(){
	$("#test").text("world");
});
</script>
	</body>
</html>
```
Run: `plackup -MPlack::App::Directory -MPlack::Builder -e 'builder{enable q{Debug}; Plack::App::Directory->new(root=>".")};'`

Point the browser to: http://localhost:5000/index.html

Got the following error (using Safari's web-inspector):
```
[Error] TypeError: b(document).bind is not a function. (In 'b(document).bind', 'b(document).bind' is undefined)
	(anonymous function) (jquery-3.1.1.slim.min.js:2:31859)
[Error] TypeError: b(document).unbind is not a function. (In 'b(document).unbind("keydown.plDebug")', 'b(document).unbind' is undefined)
	(anonymous function) (jquery-3.1.1.slim.min.js:2:31859)
```
Also, clicking the big `?` (Show Toolbar) produces more errors like:
```
[Error] TypeError: b(document).bind is not a function. (In 'b(document).bind("keydown.plDebug",function(d){if(d.keyCode==27){b.plDebug.close()}})', 'b(document).bind' is undefined)
	show_toolbar (toolbar.min.js:1:1973)
	(anonymous function) (toolbar.min.js:1:1393)
	dispatch (jquery-3.1.1.slim.min.js:3:10565)
```
No errors using jQuery `2.x` or `1.x`. Unfortunately i don't know javascript, so can't track down the problem in more details.

**Comment by DjuraDJ** [comment]
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>test</title>
</head>
	<body>
	Hello <span id="test">xxx</span>!
	<script   src="https://code.jquery.com/jquery-3.1.1.slim.min.js"   integrity="sha256-/SIrNqv8h6QGKDuNoLGA4iret+kyesCkHGzVUUV0shc="   crossorigin="anonymous"></script>


<script>
$(document).ready(function(){
	$("#test").text("world");
});
</script>
	</body>
</html>

I fixed the <!DOCTYPE html> and it says Hello World now when you load it. I tested it on chrome and Internet explore. I uncommented 2.x and 1.x all separately and everything works fine.

**Comment by jomo666** [comment]
@DjuraDJ I do not understand. What I should to do for getting the "fix"?

**Comment by jomo666** [comment]
Just tested the above today, and everything works OK. Maybe the issue is caused by Safari. Or don't know - but - because it works, closing the issue.
