### ISSUE TITLE
utf8 tests fail with Encode@2.99

### ISSUE THREAD

**Issue by veryrusty** [miyagawa/Plack-Middleware-Debug#40]
At $work we hit an issue where the `t/utf8.t` test fails when Encode v2.99 is installed. There are a small number of CPAN testers reports with the same failure, eg: http://www.cpantesters.org/cpan/report/fc05fb16-2211-11e9-aeba-d1e8b92231d7

For the time being we've pined our build to Encode@2.98 so the tests for Plack::Middleware::Debug pass. Hoping to get the chance to investigate whats causing the fail in the next few days.

**Comment by miyagawa** [comment]
Confirmed the issue. 

This should probably be reported to upstream Encode.pm. Looking at the Changes it seems to be coming from https://github.com/dankogai/p5-encode/pull/134
